name 'runthebusiness-guacamole'
version '1.0.3'

author 'runthebusiness'
license 'Apache License, Version 2.0'
project_page 'https://github.com/runthebusiness/puppet-guacamole'
source 'UNKNOWN'
summary 'This class installs and configures guacamole'
description 'guacamole

This class installs and configures guacamole

In the latest release we have removed tightvncserver from the class so you can choose whether you want to use this server or not. We there for recommend that you also use runthebusiness-tightvncserver with module.

After installing you will still need to run: tightvncserver from command line and set up it\'s password before guacamole can be used (if you are using tight vnc) -- we could not find a way to automate this part of the process.

Examples:
	tightvncserver {"installtightvncserver":
    
  	}
	guacamole{"installguacamole":
	  password=>\'examplepassword\',
	  require=>tightvncserver["installtightvncserver"]
	}


This module has been tested in debian squeeze. The init.pp and params.pp files have place-holders for the functionality to include other flavors. If you would like to contribute the code to enable these other flavors please let us know.

Authors
-------
Will Ferrer, Ethan Brooks

Licensees
-------
2012 developed under license for Switchsoft LLC http://www.switchsoft.com a "Direct response telephony company" as part of it\'s "VOIP Call distribution, ROI analysis platform, call recording, and IVR for inbound and outbound sales" and Run the Business Systems LLC a "Technology development investment group" as part of it\'s "PHP, Javascript rapid application development framework and MySQL analysis tools"

License
-------
Licensed under the terms of the Open Source LGPL 3.0 license.  


Contact
-------
will.ferrer@runthebusiness.net

Support
-------

Please send tickets and issues to our contact email address or at: https://github.com/runthebusiness/puppet-guacamole/issues

Project Url
-------
https://github.com/runthebusiness/puppet-guacamole
'
dependency 'runthebusiness/fetchfile', '==1.0.0'
